apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-python-ci-cd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-python-ci-cd-pipeline
  template:
    metadata:
      labels:
        app: vue-python-ci-cd-pipeline
    spec:
      containers:
      - name: vue-python-ci-cd-pipeline
        image: us-central1-docker.pkg.dev/ci-cd-pipeline-implementation/aliassajucicdproject/vue-python-ci-cd-appliation:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: vue-python-ci-cd-pipeline-loadbalancer
spec:
  selector:
    app: vue-python-ci-cd-pipeline
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000